In [1]:
import numpy as np

In [29]:
a = np.array([[[0.2,0],[0.4,0],[0.1,0]],
              [[0.4,1],[0.5,1],[0.4,1]],
              [[0.3,2],[0.2,2],[0.2,2]],
              [[0.7,3],[0.3,3],[0.6,3]]])

In [32]:
a

array([[[0.2, 0. ],
        [0.4, 0. ],
        [0.1, 0. ]],

       [[0.4, 1. ],
        [0.5, 1. ],
        [0.4, 1. ]],

       [[0.3, 2. ],
        [0.2, 2. ],
        [0.2, 2. ]],

       [[0.7, 3. ],
        [0.3, 3. ],
        [0.6, 3. ]]])

In [41]:
np.array(sorted(a[:,0,:],key=lambda it:it[0]))

array([[0.2, 0. ],
       [0.3, 2. ],
       [0.4, 1. ],
       [0.7, 3. ]])

In [53]:
a[:,0,:] = np.array(sorted(a[:,0,:],key=lambda it:it[0]))

In [56]:
a

array([[[0.2, 0. ],
        [0.4, 0. ],
        [0.1, 0. ]],

       [[0.3, 2. ],
        [0.5, 1. ],
        [0.4, 1. ]],

       [[0.4, 1. ],
        [0.2, 2. ],
        [0.2, 2. ]],

       [[0.7, 3. ],
        [0.3, 3. ],
        [0.6, 3. ]]])