In [8]:
import MySQLdb
import torch
import numpy as np
import matplotlib.pyplot as plt
import math

In [9]:
a = torch.arange(10)
b = 2*torch.arange(10)

In [10]:
c = torch.empty(10,2)
c[:,0] = a
c[:,1] = b

In [11]:
c

tensor([[ 0.,  0.],
        [ 1.,  2.],
        [ 2.,  4.],
        [ 3.,  6.],
        [ 4.,  8.],
        [ 5., 10.],
        [ 6., 12.],
        [ 7., 14.],
        [ 8., 16.],
        [ 9., 18.]])

In [12]:
448./510.-32./39.+32./(17.*27.)

0.12763532763532764

In [23]:
b0 = c[:,0]>3
b1 = c[:,0]<8
b0

tensor([False, False, False, False,  True,  True,  True,  True,  True,  True])

In [24]:
b1

tensor([ True,  True,  True,  True,  True,  True,  True,  True, False, False])

In [25]:
b0==b1

tensor([False, False, False, False,  True,  True,  True,  True, False, False])

In [33]:
k = None
k is not None

False

In [40]:
np.linspace(1,9-1,9-1)

array([1., 2., 3., 4., 5., 6., 7., 8.])