In [1]:
import numpy as np
import stock
from datetime import date,datetime
import kline
import test

1.115861177444458


In [2]:
a = np.arange(14).reshape(2,7)

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [21]:
b = np.arange(7).reshape(1,7)

In [22]:
b

array([[0, 1, 2, 3, 4, 5, 6]])

In [23]:
b[0][0] = 10

In [24]:
b

array([[10,  1,  2,  3,  4,  5,  6]])

In [27]:
b = np.vstack(([[10,  1,  2,  3,  4,  5,  6]],a))

In [28]:
b

array([[10,  1,  2,  3,  4,  5,  6],
       [ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [32]:
np.flip(b,0)

array([[ 7,  8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5,  6],
       [10,  1,  2,  3,  4,  5,  6]])